# Generated by Django 2.2.13 on 2020-10-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="language",
            options={"verbose_name": "language", "verbose_name_plural": "languages"},
        ),
        migrations.AlterField(
            model_name="language",
            name="alpha_3_code",
            field=models.CharField(
                blank=True,
                help_text="ISO 639-3 (language) or ISO 639-5 (language family) alpha-3 code",
                max_length=3,
                null=True,
                unique=True,
                verbose_name="alpha-3 code",
            ),
        ),
    ]
