# Generated by Django 2.2.10 on 2020-03-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_modify_venues_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuetranslation",
            name="wc_and_facilities",
            field=models.TextField(blank=True, verbose_name="WC & facilities"),
        ),
    ]
