# Generated by Django 2.2.6 on 2019-11-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0002_add_guardian")]

    operations = [migrations.RemoveField(model_name="guardian", name="email")]
