# Generated by Django 2.2.6 on 2019-11-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0003_remove_guardian_email")]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="language",
            field=models.CharField(blank=True, max_length=10, verbose_name="language"),
        )
    ]
