# Generated by Django 2.2.10 on 2020-05-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_guardian_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
