# Generated by Django 2.2.9 on 2020-01-23 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_add_translations_field"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="duration",),
        migrations.AddField(
            model_name="event",
            name="capacity_per_occurrence",
            field=models.PositiveSmallIntegerField(
                verbose_name="capacity per occurrence"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, upload_to="", verbose_name="image"),
        ),
        migrations.AddField(
            model_name="event",
            name="participants_per_invite",
            field=models.CharField(
                choices=[
                    ("child_and_guardian", "Child and " "Guardian"),
                    ("family", "Family"),
                ],
                max_length=255,
                verbose_name="participants per invite",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="published at"
            ),
        ),
    ]
