# Generated by Django 2.2.9 on 2020-02-07 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0004_add_child_postal_code"),
        ("events", "0005_delete_old_duration_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrolment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolments",
                        to="children.Child",
                        verbose_name="child",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolments",
                        to="events.Occurrence",
                        verbose_name="occurrence",
                    ),
                ),
            ],
            options={"verbose_name": "enrolment", "verbose_name_plural": "enrolments",},
        ),
        migrations.AddField(
            model_name="occurrence",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                related_name="occurrences",
                through="events.Enrolment",
                to="children.Child",
                verbose_name="children",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrolment",
            constraint=models.UniqueConstraint(
                fields=("child", "occurrence"), name="unq_child_occurrence"
            ),
        ),
    ]
