# Generated by Django 2.2.10 on 2020-03-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_eventtranslation_image_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtranslation",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="name"),
        ),
    ]
