# Generated by Django 2.2.13 on 2020-09-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_add_choice_child_and_1_or_2_guardians"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="capacity_override",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="When set will be used as the capacity of this occurrence instead of the value coming from the event.",
                null=True,
                verbose_name="capacity override",
            ),
        ),
    ]
