# Generated by Django 2.2.13 on 2020-09-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_add_occurrence_capacity_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="reminder sent at"
            ),
        ),
    ]
