# Generated by Django 2.2.13 on 2020-12-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_add_event_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ready_for_event_group_publishing",
            field=models.BooleanField(
                default=False, verbose_name="ready for event group publishing"
            ),
        ),
    ]
