# Generated by Django 2.2.13 on 2020-12-29 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_add_event_ready_for_event_group_publishing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrolment",
            name="child",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrolments",
                to="children.Child",
                verbose_name="child",
            ),
        ),
    ]
