# Generated by Django 2.2.10 on 2020-04-08 08:26

from django.conf import settings
from django.db import migrations, models


def create_first_project(apps, schema_editor):
    apps.get_model("projects", "Project").objects.create(year=2020)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(verbose_name="year", unique=True),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="users",
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "ordering": ["year"],
            },
        ),
        migrations.RunPython(create_first_project, migrations.RunPython.noop),
    ]
