# Generated by Django 2.2.10 on 2020-05-04 06:30

from django.db import migrations, models
import django.db.models.deletion

PROJECT_NAME_2020 = (
    ("fi", "Helsingin kaupunginorkesteri"),
    ("sv", "Helsingfors stadsorkester"),
    ("en", "Helsinki Philharmonic Orchestra"),
)


def populate_name_for_year_2020(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ProjectTranslation = apps.get_model("projects", "ProjectTranslation")

    try:
        project_2020 = Project.objects.get(year=2020)
    except Project.DoesNotExist:
        return

    for language_code, name in PROJECT_NAME_2020:
        ProjectTranslation.objects.create(
            master_id=project_2020.pk, language_code=language_code, name=name,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="projects.Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "project Translation",
                "db_table": "projects_project_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
        migrations.RunPython(populate_name_for_year_2020, migrations.RunPython.noop),
    ]
