# Generated by Django 2.2.13 on 2020-12-23 10:14

from django.db import migrations
from guardian.shortcuts import assign_perm


def assign_project_permissions(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all():
        for user in project.users.all():
            assign_perm


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_upgrade_to_parler_2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["year"],
                "permissions": (
                    ("admin", "Base admin permission"),
                    ("publish", "Can publish"),
                ),
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
    ]
