# Common errors
GENERAL_ERROR = "GENERAL_ERROR"
PERMISSION_DENIED_ERROR = "PERMISSION_DENIED_ERROR"
OBJECT_DOES_NOT_EXIST_ERROR = "OBJECT_DOES_NOT_EXIST_ERROR"
DATA_VALIDATION_ERROR = "DATA_VALIDATION_ERROR"
API_USAGE_ERROR = "API_USAGE_ERROR"
QUERY_TOO_DEEP_ERROR = "QUERY_TOO_DEEP_ERROR"

# Kukkuu specific errors
MAX_NUMBER_OF_CHILDREN_PER_GUARDIAN_ERROR = "MAX_NUMBER_OF_CHILDREN_PER_GUARDIAN_ERROR"
CHILD_ALREADY_JOINED_EVENT_ERROR = "CHILD_ALREADY_JOINED_EVENT_ERROR"
PAST_OCCURRENCE_ERROR = "PAST_OCCURRENCE_ERROR"
OCCURRENCE_IS_FULL_ERROR = "OCCURRENCE_IS_FULL_ERROR"
EVENT_ALREADY_PUBLISHED_ERROR = "EVENT_ALREADY_PUBLISHED_ERROR"
MISSING_DEFAULT_TRANSLATION_ERROR = "MISSING_DEFAULT_TRANSLATION_ERROR"
INELIGIBLE_OCCURRENCE_ENROLMENT = "INELIGIBLE_OCCURRENCE_ENROLMENT"
INVALID_EMAIL_FORMAT_ERROR = "INVALID_EMAIL_FORMAT_ERROR"
