# Generated by Django 2.2.13 on 2020-08-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
        ("children", "0005_child_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="languages_spoken_at_home",
            field=models.ManyToManyField(
                blank=True,
                related_name="children",
                to="languages.Language",
                verbose_name="languages spoken at home",
            ),
        ),
    ]
